# Site settings
title: Telostat Pte Ltd
email: info@telostat.com
description: > # this means to ignore newlines until "baseurl:"
    Telostat is a technology and R&D services
    company providing computational and
    method-dependent solutions for data and
    process-intensive businesses.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.telostat.com" # the base hostname & protocol for your site
twitter_username: telostat
github_username:  telostat

# Build settings
markdown: kramdown
